site_name: noaa-fisheries-globus

repo_url: github.com/nodd-tools/noaa-fisheries-globus

theme:
  name: material
  features:
    - navigation.tabs
    - content.code.annotate
  markdown_extensions:
    - markdown.extensions.admonition
    - markdown.extensions.codehilite
    - pymdownx.superfences

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            docstring_style: numpy

nav:
  - Home: README.md
  - Contributing: CONTRIBUTING.md
  - Code of Conduct: CODE_OF_CONDUCT.md
